export const COUNTRIES = [
  // 🔥 TOP ELITE
  {
    _id: "arg",
    name: "Argentina",
    shortName: "ARG",
    logoUrl: "https://flagcdn.com/ar.svg",
    probability: 1,
  },
  {
    _id: "bra",
    name: "Brasil",
    shortName: "BRA",
    logoUrl: "https://flagcdn.com/br.svg",
    probability: 1,
  },
  {
    _id: "fra",
    name: "Francia",
    shortName: "FRA",
    logoUrl: "https://flagcdn.com/fr.svg",
    probability: 1,
  },
  {
    _id: "ger",
    name: "Alemania",
    shortName: "GER",
    logoUrl: "https://flagcdn.com/de.svg",
    probability: 1,
  },
  {
    _id: "spa",
    name: "España",
    shortName: "ESP",
    logoUrl: "https://flagcdn.com/es.svg",
    probability: 1,
  },
  {
    _id: "eng",
    name: "Inglaterra",
    shortName: "ENG",
    logoUrl: "https://flagcdn.com/gb-eng.svg",
    probability: 1,
  },

  // 🔥 MUY FUERTES
  {
    _id: "ita",
    name: "Italia",
    shortName: "ITA",
    logoUrl: "https://flagcdn.com/it.svg",
    probability: 0.9,
  },
  {
    _id: "ned",
    name: "Países Bajos",
    shortName: "NED",
    logoUrl: "https://flagcdn.com/nl.svg",
    probability: 0.9,
  },
  {
    _id: "por",
    name: "Portugal",
    shortName: "POR",
    logoUrl: "https://flagcdn.com/pt.svg",
    probability: 0.85,
  },
  {
    _id: "uru",
    name: "Uruguay",
    shortName: "URU",
    logoUrl: "https://flagcdn.com/uy.svg",
    probability: 0.85,
  },

  // 🔥 COMPETITIVOS
  {
    _id: "cro",
    name: "Croacia",
    shortName: "CRO",
    logoUrl: "https://flagcdn.com/hr.svg",
    probability: 0.8,
  },
  {
    _id: "bel",
    name: "Bélgica",
    shortName: "BEL",
    logoUrl: "https://flagcdn.com/be.svg",
    probability: 0.8,
  },
  {
    _id: "den",
    name: "Dinamarca",
    shortName: "DEN",
    logoUrl: "https://flagcdn.com/dk.svg",
    probability: 0.75,
  },
  {
    _id: "col",
    name: "Colombia",
    shortName: "COL",
    logoUrl: "https://flagcdn.com/co.svg",
    probability: 0.75,
  },
  {
    _id: "chi",
    name: "Chile",
    shortName: "CHI",
    logoUrl: "https://flagcdn.com/cl.svg",
    probability: 0.75,
  },
  {
    _id: "mex",
    name: "México",
    shortName: "MEX",
    logoUrl: "https://flagcdn.com/mx.svg",
    probability: 0.75,
  },

  // 🔥 MEDIOS
  {
    _id: "usa",
    name: "Estados Unidos",
    shortName: "USA",
    logoUrl: "https://flagcdn.com/us.svg",
    probability: 0.7,
  },
  {
    _id: "jpn",
    name: "Japón",
    shortName: "JPN",
    logoUrl: "https://flagcdn.com/jp.svg",
    probability: 0.7,
  },
  {
    _id: "kor",
    name: "Corea del Sur",
    shortName: "KOR",
    logoUrl: "https://flagcdn.com/kr.svg",
    probability: 0.7,
  },
  {
    _id: "mar",
    name: "Marruecos",
    shortName: "MAR",
    logoUrl: "https://flagcdn.com/ma.svg",
    probability: 0.7,
  },
  {
    _id: "sen",
    name: "Senegal",
    shortName: "SEN",
    logoUrl: "https://flagcdn.com/sn.svg",
    probability: 0.7,
  },

  // 🔥 LATAM EXTRA
  {
    _id: "per",
    name: "Perú",
    shortName: "PER",
    logoUrl: "https://flagcdn.com/pe.svg",
    probability: 0.65,
  },
  {
    _id: "ecu",
    name: "Ecuador",
    shortName: "ECU",
    logoUrl: "https://flagcdn.com/ec.svg",
    probability: 0.65,
  },
  {
    _id: "par",
    name: "Paraguay",
    shortName: "PAR",
    logoUrl: "https://flagcdn.com/py.svg",
    probability: 0.65,
  },
  {
    _id: "bol",
    name: "Bolivia",
    shortName: "BOL",
    logoUrl: "https://flagcdn.com/bo.svg",
    probability: 0.5,
  },
  {
    _id: "ven",
    name: "Venezuela",
    shortName: "VEN",
    logoUrl: "https://flagcdn.com/ve.svg",
    probability: 0.5,
  },

  // 🔥 EUROPA MEDIA
  {
    _id: "sui",
    name: "Suiza",
    shortName: "SUI",
    logoUrl: "https://flagcdn.com/ch.svg",
    probability: 0.7,
  },
  {
    _id: "aut",
    name: "Austria",
    shortName: "AUT",
    logoUrl: "https://flagcdn.com/at.svg",
    probability: 0.65,
  },
  {
    _id: "swe",
    name: "Suecia",
    shortName: "SWE",
    logoUrl: "https://flagcdn.com/se.svg",
    probability: 0.65,
  },
  {
    _id: "nor",
    name: "Noruega",
    shortName: "NOR",
    logoUrl: "https://flagcdn.com/no.svg",
    probability: 0.6,
  },
  {
    _id: "pol",
    name: "Polonia",
    shortName: "POL",
    logoUrl: "https://flagcdn.com/pl.svg",
    probability: 0.65,
  },

  // 🔥 AFRICA
  {
    _id: "gha",
    name: "Ghana",
    shortName: "GHA",
    logoUrl: "https://flagcdn.com/gh.svg",
    probability: 0.65,
  },
  {
    _id: "civ",
    name: "Costa de Marfil",
    shortName: "CIV",
    logoUrl: "https://flagcdn.com/ci.svg",
    probability: 0.65,
  },
  {
    _id: "nga",
    name: "Nigeria",
    shortName: "NGA",
    logoUrl: "https://flagcdn.com/ng.svg",
    probability: 0.65,
  },
  {
    _id: "tun",
    name: "Túnez",
    shortName: "TUN",
    logoUrl: "https://flagcdn.com/tn.svg",
    probability: 0.6,
  },
  {
    _id: "alg",
    name: "Argelia",
    shortName: "ALG",
    logoUrl: "https://flagcdn.com/dz.svg",
    probability: 0.6,
  },

  // 🔥 ASIA / OTROS
  {
    _id: "aus",
    name: "Australia",
    shortName: "AUS",
    logoUrl: "https://flagcdn.com/au.svg",
    probability: 0.65,
  },
  {
    _id: "qat",
    name: "Qatar",
    shortName: "QAT",
    logoUrl: "https://flagcdn.com/qa.svg",
    probability: 0.5,
  },
  {
    _id: "uae",
    name: "Emiratos Árabes",
    shortName: "UAE",
    logoUrl: "https://flagcdn.com/ae.svg",
    probability: 0.5,
  },
  {
    _id: "chn",
    name: "China",
    shortName: "CHN",
    logoUrl: "https://flagcdn.com/cn.svg",
    probability: 0.4,
  },
  {
    _id: "ind",
    name: "India",
    shortName: "IND",
    logoUrl: "https://flagcdn.com/in.svg",
    probability: 0.3,
  },

  // 🔥 RANDOM EXTRA
  {
    _id: "can",
    name: "Canadá",
    shortName: "CAN",
    logoUrl: "https://flagcdn.com/ca.svg",
    probability: 0.6,
  },
  {
    _id: "irl",
    name: "Irlanda",
    shortName: "IRL",
    logoUrl: "https://flagcdn.com/ie.svg",
    probability: 0.55,
  },
  {
    _id: "sco",
    name: "Escocia",
    shortName: "SCO",
    logoUrl: "https://flagcdn.com/gb-sct.svg",
    probability: 0.55,
  },
  {
    _id: "fin",
    name: "Finlandia",
    shortName: "FIN",
    logoUrl: "https://flagcdn.com/fi.svg",
    probability: 0.5,
  },
  {
    _id: "cze",
    name: "República Checa",
    shortName: "CZE",
    logoUrl: "https://flagcdn.com/cz.svg",
    probability: 0.6,
  },
];
